- name: Install Calibre
  run: |
    sudo -v
    wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

- name: Convert EPUBs to EPUB 3
  run: |
    mkdir -p books_fixed
    for epub in books/*.epub; do
      ebook-convert "$epub" "books_fixed/$(basename "$epub")" --epub-version 3
    done
    rm -rf books
    mv books_fixed books
